<a href="https://colab.research.google.com/github/naman-0804/learning/blob/deep-learning/deeplearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [85]:
#pip install tensorflow

In [86]:
import tensorflow as tf
print(tf.__version__)

2.20.0

In [87]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [88]:
dataset=pd.read_csv('Churn_Modelling.csv')
dataset.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [89]:
##Divide the dataset into independent and dependent features
X=dataset.iloc[:,3:13]
y=dataset.iloc[:,13]

In [90]:
X.head() ##independent feature

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [91]:
y.head() ##dependent feature

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [92]:
##takes distinct values in that coloumn and makes a binary table of that (present in which row) drop_first removes 1st coloumn , if other two are  0 0 means 1st is 1
geography=pd.get_dummies(X['Geography'],drop_first=True)
gender=pd.get_dummies(X['Gender'],drop_first=True)

In [93]:
##Concatenate these var with data frame
X=X.drop(['Geography','Gender'],axis=1) ##axis removes coloumn

In [94]:
X.head()

   CreditScore  Age  Tenure  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619   42       2  ...          1               1        101348.88
1          608   41       1  ...          0               1        112542.58
2          502   42       8  ...          1               0        113931.57
3          699   39       1  ...          0               0         93826.63
4          850   43       2  ...          1               1         79084.10

[5 rows x 8 columns]

In [95]:
X=pd.concat([X,geography,gender],axis=1) ##removed 2 coloumns efficiently
X.head()

   CreditScore  Age  Tenure    Balance  ...  EstimatedSalary  Germany  Spain   Male
0          619   42       2       0.00  ...        101348.88    False  False  False
1          608   41       1   83807.86  ...        112542.58    False   True  False
2          502   42       8  159660.80  ...        113931.57    False  False  False
3          699   39       1       0.00  ...         93826.63    False  False  False
4          850   43       2  125510.82  ...         79084.10    False   True  False

[5 rows x 11 columns]

In [96]:
##Splitting the dataset into training set and Test set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [97]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [98]:
X_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [99]:
X_train.shape

(8000, 11)

## **Part 2 , ANN**

In [100]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LeakyReLU,PReLU,ELU,ReLU
from tensorflow.keras.layers import Dropout

In [101]:
# initialize the ANN
classifier=Sequential()

In [102]:
# Adding the input layer
classifier.add(Dense(units=11,activation='relu'))

In [103]:
#adding first hidden layer
classifier.add(Dense(units=7,activation='relu'))

In [104]:
#adding second hidden layer
classifier.add(Dense(units=6,activation='relu'))

In [105]:
#adding output layer
classifier.add(Dense(units=1,activation='sigmoid'))

In [106]:
#compile
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [110]:
#model_history=classifier.fit(X_train,y_train,validation_split=0.33,batch_size=10,epochs=1000) #no need for 1000 as stable acc so stop at somwehere

Epoch 1/5
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8658 - loss: 0.3145 - val_accuracy: 0.8542 - val_loss: 0.3611
Epoch 2/5
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8673 - loss: 0.3149 - val_accuracy: 0.8535 - val_loss: 0.3610
Epoch 3/5
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8692 - loss: 0.3140 - val_accuracy: 0.8569 - val_loss: 0.3615
Epoch 4/5
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8694 - loss: 0.3135 - val_accuracy: 0.8523 - val_loss: 0.3643
Epoch 5/5
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8675 - loss: 0.3145 - val_accuracy: 0.8573 - val_loss: 0.3614

In [114]:
#early stopping
from tensorflow.keras.callbacks import EarlyStopping
early_stopping=EarlyStopping(monitor='val_loss',min_delta=0.0001,patience=20,verbose=1,mode='auto',restore_best_weights=False)

In [115]:
model_history=classifier.fit(X_train,y_train,validation_split=0.33,batch_size=10,epochs=1000,callbacks=early_stopping)

Epoch 1/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8686 - loss: 0.3135 - val_accuracy: 0.8531 - val_loss: 0.3618
Epoch 2/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8681 - loss: 0.3135 - val_accuracy: 0.8538 - val_loss: 0.3628
Epoch 3/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8675 - loss: 0.3119 - val_accuracy: 0.8504 - val_loss: 0.3638
Epoch 4/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8668 - loss: 0.3128 - val_accuracy: 0.8527 - val_loss: 0.3613
Epoch 5/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8671 - loss: 0.3130 - val_accuracy: 0.8542 - val_loss: 0.3618
Epoch 6/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8660 - loss: 0.3126 - val_accuracy: 0.8531 - val_loss: 0.3647
Epoch 7/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8684 - loss: 0.3122 - val_accuracy: 0.8538 - val_loss: 0.3623
Epoch 8/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8686 - loss: 0.3116 - val_accuracy: 0.8535 - val_loss: 0.3629
Epoch 9/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8720 - loss: 0.3104 - val_accuracy: 0.8531 - val_loss: 0.3673
Epoch 10/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8690 - loss: 0.3120 - val_accuracy: 0.8508 - val_loss: 0.3631
Epoch 11/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8699 - loss: 0.3121 - val_accuracy: 0.8546 - val_loss: 0.3649
Epoch 12/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8688 - loss: 0.3110 - val_accuracy: 0.8573 - val_loss: 0.3608
Epoch 13/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8673 - loss: 0.3114 - val_accuracy: 0.8580 - val_loss: 0.3637
Epoch 14/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8709 - loss: 0.3106 - val_accuracy: 0.8565 - val_loss: 0.3631
Epoch 15/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8677 - loss: 0.3104 - val_accuracy: 0.8535 - val_loss: 0.3660
Epoch 16/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8670 - loss: 0.3104 - val_accuracy: 0.8538 - val_loss: 0.3672
Epoch 17/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8684 - loss: 0.3113 - val_accuracy: 0.8531 - val_loss: 0.3662
Epoch 18/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8671 - loss: 0.3097 - val_accuracy: 0.8550 - val_loss: 0.3635
Epoch 19/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8707 - loss: 0.3093 - val_accuracy: 0.8542 - val_loss: 0.3626
Epoch 20/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8686 - loss: 0.3092 - val_accuracy: 0.8557 - val_loss: 0.3620
Epoch 21/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8694 - loss: 0.3095 - val_accuracy: 0.8527 - val_loss: 0.3648
Epoch 22/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8681 - loss: 0.3096 - val_accuracy: 0.8576 - val_loss: 0.3639
Epoch 23/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8712 - loss: 0.3091 - val_accuracy: 0.8569 - val_loss: 0.3638
Epoch 24/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8709 - loss: 0.3086 - val_accuracy: 0.8573 - val_loss: 0.3638
Epoch 25/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8701 - loss: 0.3088 - val_accuracy: 0.8538 - val_loss: 0.3672
Epoch 26/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8727 - loss: 0.3080 - val_accuracy: 0.8557 - val_loss: 0.3682
Epoch 27/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8716 - loss: 0.3077 - val_accuracy: 0.8569 - val_loss: 0.3629
Epoch 28/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8709 - loss: 0.3093 - val_accuracy: 0.8542 - val_loss: 0.3630
Epoch 29/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8698 - loss: 0.3084 - val_accuracy: 0.8557 - val_loss: 0.3633
Epoch 30/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8694 - loss: 0.3080 - val_accuracy: 0.8550 - val_loss: 0.3638
Epoch 31/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8690 - loss: 0.3085 - val_accuracy: 0.8580 - val_loss: 0.3632
Epoch 32/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8698 - loss: 0.3077 - val_accuracy: 0.8535 - val_loss: 0.3650
Epoch 32: early stopping